# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1696858935);
user_pref("app.update.lastUpdateTime.background-update-timer", 1696858780);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1696859055);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1696869859);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1696858668);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtab.choice", 4);
user_pref("browser.newtab.url", "about:newtab");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.defaultenginename", "Google");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 1342);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "file:///C:/ff/page.xht");
user_pref("browser.startup.homepage_override.buildID", "20210723224757");
user_pref("browser.startup.homepage_override.mstone", "4.8.2");
user_pref("devtools.styleeditor.mediaSidebarWidth", 104);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_OS_ENUMERATED_PER_USER\":\"29.3.0\",\"DEVTOOLS_OS_IS_64_BITS_PER_USER\":\"29.3.0\",\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"29.3.0\"}");
user_pref("devtools.toolbox.host", "window");
user_pref("devtools.toolbox.previousHost", "bottom");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 350);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B9e96e0c4-9bde-49b7-989f-a4ca4bdc90bb%7D:1.5.11,%7B74c822b8-b6d5-4a81-872c-067338334a74%7D:1.4.1,%7B3B9A302B-BD28-5D2F-9C6A-5D0C6058A8AF%7D:3.0,%7B0ed852bb-a216-42e9-b98e-98e62085837f%7D:2.6.1");
user_pref("extensions.lastAppVersion", "29.3.0");
user_pref("extensions.lastPlatformVersion", "4.8.2");
user_pref("extensions.palesomething.lists.names", "fox");
user_pref("extensions.palesomething.lists.prefixes", "Fire");
user_pref("extensions.palesomething.lists.vendors", "Mozilla");
user_pref("extensions.palesomething.samename", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.showdownloadswts.firstRun", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{0ed852bb-a216-42e9-b98e-98e62085837f}\":{\"d\":\"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Mypal\\\\Profiles\\\\ilb4xz0v.default\\\\extensions\\\\{0ed852bb-a216-42e9-b98e-98e62085837f}.xpi\",\"e\":true,\"v\":\"2.6.1\",\"st\":1689974914546},\"{3B9A302B-BD28-5D2F-9C6A-5D0C6058A8AF}\":{\"d\":\"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Mypal\\\\Profiles\\\\ilb4xz0v.default\\\\extensions\\\\{3B9A302B-BD28-5D2F-9C6A-5D0C6058A8AF}.xpi\",\"e\":true,\"v\":\"3.0\",\"st\":1689974745128},\"{74c822b8-b6d5-4a81-872c-067338334a74}\":{\"d\":\"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Mypal\\\\Profiles\\\\ilb4xz0v.default\\\\extensions\\\\{74c822b8-b6d5-4a81-872c-067338334a74}.xpi\",\"e\":true,\"v\":\"1.4.1\",\"st\":1689974745116},\"{9e96e0c4-9bde-49b7-989f-a4ca4bdc90bb}\":{\"d\":\"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Mypal\\\\Profiles\\\\ilb4xz0v.default\\\\extensions\\\\{9e96e0c4-9bde-49b7-989f-a4ca4bdc90bb}.xpi\",\"e\":true,\"v\":\"1.5.11\",\"st\":1689974745104}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\old firefox\\\\Mypal\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":false,\"v\":\"29.3.0\",\"st\":1627118412000}}}");
user_pref("general.skins.selectedSkin", "mf3");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "29.3.0");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x1c82");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "30.0.14.9649");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d11video", 2);
user_pref("idle.lastDailyNotification", 1696859236);
user_pref("media.benchmark.vp9.fps", 180);
user_pref("media.benchmark.vp9.versioncheck", 3);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1696573989);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x1c82");
user_pref("sanity-test.driver-version", "30.0.14.9649");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210723224757");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 8);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1696573989);
user_pref("toolkit.startup.last_success", 1696922938);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
